# Generated by Django 3.0.7 on 2020-07-01 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghumo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destin',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
